name: nblint

description: Lint jupyter notebooks to ensure proper formatting

inputs:
  directory:
    description: Directory to search for notebooks
    required: false
    default: '.'
  ignore_paths:
    description: Comma-seperated list of paths to ignore
    required: false
    default: ''
  check_outputs_empty:
    description: Check that output cell are empty
    required: false
    default: true
  check_no_trailing_newline:
    description: Check that there is no newline at the end of code cells
    required: false
    default: true
  check_correct_kernel:
    description: Check that notebook is using the right kernel
    required: false
    default: false
  check_notebook_badge:
    description: Check that notebook has a google colab badge 
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: pip install -r '${{ github.action_path }}/requirements.txt'
      shell: bash
    - name: Run nblint script
      run: python '${{ github.action_path }}/src/nblint.py'
      shell: bash
      env:
        INPUT_DIRECTORY: ${{ inputs.directory }}
        INPUT_IGNORE_PATHS: ${{ inputs.ignore_paths }}
        INPUT_CHECK_OUTPUTS_EMPTY: ${{ inputs.check_outputs_empty }}
        INPUT_CHECK_NO_TRAILING_NEWLINE: ${{ inputs.check_no_trailing_newline }}
        INPUT_CHECK_CORRECT_KERNEL: ${{ inputs.check_correct_kernel }}
        INPUT_CHECK_NOTEBOOK_BADGE: ${{ inputs.check_notebook_badge }}